# -*- coding: utf-8 -*-
"""RB3D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aw7LhLKzynpA5y7zhA229INEmA_G2LC6

sources used to make this code:
https://github.com/pytorch/vision/blob/e6b4078ec73c2cf4fd4432e19c782db58719fb99/torchvision/models/resnet.py
https://jarvislabs.ai/blogs/resnet
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import random

class SCNN(nn.Module):
    def __init__(self, num_classes=10):
        super(SCNN, self).__init__()

        # dimensions of the 3D image. Channels, Depth, Height, Width
        C = 1
        D = 32
        H = 32
        W = 32

        self.conv1 = nn.Conv3d(C, 32, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv3d(32, 32, kernel_size=3, stride=1, padding=1)
        self.batchnorm_conv2 = nn.BatchNorm3d(num_features=32)

        self.conv3 = nn.Conv3d(32, 64, kernel_size=3, stride=1, padding=1)
        self.conv4 = nn.Conv3d(64, 64, kernel_size=3, stride=1, padding=1)
        self.batchnorm_conv4 = nn.BatchNorm3d(num_features=64)

        self.fc1 = nn.Linear( (D*H*W*64) // (8*8), 512)
        self.fc2 = nn.Linear(512 , 512)
        self.fc3 = nn.Linear(512 , num_classes)

    def forward(self, x):

        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = self.batchnorm_conv2(x)
        x = F.max_pool3d(x, kernel_size=2, stride=2, padding=0)

        x = F.relu(self.conv3(x))
        x = F.relu(self.conv4(x))
        x = self.batchnorm_conv4(x)
        x = F.max_pool3d(x, kernel_size=2, stride=2, padding=0)

        x = x.view(-1, (32*32*32*64) // (8*8))

        x = F.relu(self.fc1(x))

        x = F.dropout(x, p=0.5)

        x = F.relu(self.fc2(x))
        x = F.dropout(x, p=0.5)

        x = self.fc3(x)

        return x
